In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
movies = pd.read_csv('qEHqag.csv')

In [7]:
data = movies

In [9]:
data

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [13]:
data.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [19]:
data['Released_Year']

0      1994
1      1972
2      2008
3      1974
4      1957
       ...
995    1961
996    1956
997    1953
998    1944
999    1935
Name: Released_Year, Length: 1000, dtype: object

In [57]:
data[data["Released_Year"] == '2001']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
95,AmÃ©lie,2001,122,Comedy,8.3,Jean-Pierre Jeunet,Audrey Tautou,703810,33225499.0,69.0
159,A Beautiful Mind,2001,135,Biography,8.2,Ron Howard,Russell Crowe,848920,170742341.0,72.0
240,Dil Chahta Hai,2001,183,Comedy,8.1,Farhan Akhtar,Aamir Khan,66803,300000.0,NaN
245,"Monsters, Inc.",2001,92,Animation,8.1,Pete Docter,David Silverman,815505,289916256.0,79.0
247,Lagaan: Once Upon a Time in India,2001,224,Adventure,8.1,Ashutosh Gowariker,Aamir Khan,105036,70147.0,84.0
379,Yeopgijeogin geunyeo,2001,137,Comedy,8.0,Jae-young Kwak,Tae-Hyun Cha,45403,772721890.0,NaN
381,Vizontele,2001,110,Comedy,8.0,Yilmaz Erdogan,Ã–mer Faruk Sorak,33592,200178699.0,NaN
382,Donnie Darko,2001,113,Drama,8.0,Richard Kelly,Jake Gyllenhaal,740086,1480006.0,88.0
509,No Man's Land,2001,98,Comedy,7.9,Danis Tanovic,Branko Djuric,44618,1059830.0,84.0
510,Cowboy Bebop: Tengoku no tobira,2001,115,Animation,7.9,Shin'ichirÃ´ Watanabe,Tensai Okamura,42897,1000045.0,61.0
515,Mulholland Dr.,2001,147,Drama,7.9,David Lynch,Naomi Watts,322031,7220243.0,85.0
643,Waking Life,2001,99,Animation,7.8,Richard Linklater,Ethan Hawke,60684,2892011.0,83.0
651,Shrek,2001,90,Animation,7.8,Andrew Adamson,Vicky Jenson,613941,267665011.0,84.0
788,I Am Sam,2001,132,Drama,7.7,Jessie Nelson,Sean Penn,142863,40311852.0,28.0
790,Black Hawk Down,2001,144,Drama,7.7,Ridley Scott,Josh Hartnett,364254,108638745.0,74.0
792,Das Experiment,2001,120,Drama,7.7,Oliver Hirschbiegel,Moritz Bleibtreu,90842,141072.0,60.0
794,Hedwig and the Angry Inch,2001,95,Comedy,7.7,John Cameron Mitchell,John Cameron Mitchell,31957,3029081.0,85.0
795,Ocean's Eleven,2001,116,Crime,7.7,Steven Soderbergh,George Clooney,516372,183417150.0,74.0
802,Training Day,2001,122,Crime,7.7,Antoine Fuqua,Denzel Washington,390247,76631907.0,69.0
945,The Royal Tenenbaums,2001,110,Comedy,7.6,Wes Anderson,Gene Hackman,266842,52364010.0,76.0
946,Y tu mamÃ¡ tambiÃ©n,2001,106,Drama,7.6,Alfonso CuarÃ³n,Maribel VerdÃº,115827,13622333.0,88.0
947,Harry Potter and the Sorcerer's Stone,2001,152,Adventure,7.6,Chris Columbus,Daniel Radcliffe,658185,317575550.0,64.0
948,The Others,2001,101,Horror,7.6,Alejandro AmenÃ¡bar,Nicole Kidman,337651,96522687.0,74.0
949,Blow,2001,124,Biography,7.6,Ted Demme,Johnny Depp,240714,52990775.0,52.0
950,Enemy at the Gates,2001,131,Drama,7.6,Jean-Jacques Annaud,Jude Law,243729,51401758.0,53.0

In [91]:
xd = data[data["Released_Year"] == '2014']
xd[xd["Genre"] == 'Action'] 
# iss tarah kar sakte hain ham access 2 columns ko access
# yahan pe release year aur genre dono ko aik saath kara hai
# iska masla ye hai ke ham baar baar variables nhi bana sakte kiun ke woh memory consume karta hai zyada

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
201,Haider,2014,160,Action,8.1,Vishal Bhardwaj,Shahid Kapoor,50445,901610.0,NaN
337,Serbuan maut 2: Berandal,2014,150,Action,8.0,Gareth Evans,Iko Uwais,114316,2625803.0,71.0
339,Guardians of the Galaxy,2014,121,Action,8.0,James Gunn,Chris Pratt,1043455,333176600.0,76.0
479,X-Men: Days of Future Past,2014,132,Action,7.9,Bryan Singer,Patrick Stewart,659763,233921534.0,75.0
482,Edge of Tomorrow,2014,113,Action,7.9,Doug Liman,Tom Cruise,600004,100206256.0,71.0
730,Kingsman: The Secret Service,2014,129,Action,7.7,Matthew Vaughn,Colin Firth,590440,128261724.0,60.0
737,Captain America: The Winter Soldier,2014,136,Action,7.7,Anthony Russo,Joe Russo,736182,259766572.0,70.0
898,Dawn of the Planet of the Apes,2014,130,Action,7.6,Matt Reeves,Gary Oldman,411599,208545589.0,79.0

In [115]:
data[data['Released_Year'] == '2014'][data[data['Released_Year'] == '2014']['Director'] == 'Don Hall']
# ye zyada efficient tareeqa hai 2 columns ko access karne ka

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
592,Big Hero 6,2014,102,Animation,7.8,Don Hall,Chris Williams,410983,222527828.0,74.0